"""empty message

Revision ID: 8e36296d772d
Revises: 0f6a6df0be34
Create Date: 2022-06-07 22:55:01.669193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e36296d772d'
down_revision = '0f6a6df0be34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created')
    op.drop_column('Artist', 'created')
    # ### end Alembic commands ###
